config/routes.rb
Rails.application.routes.draw do
  root to: 'notes#index'
  resources :notes do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true

  def self.search(search)
    if search != ""
      Note.where('text LIKE(?)', "%#{search}%")
    else
      Note.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :basic_auth
  protect_from_forgery
  def index
    @notes = Note.all.order("created_at DESC")
    @note = Note.new
  end

  def show
    @note = Note.find(params[:id])
    text = @note.text
    @all_title = Note.where.not(title: @note.title)
    #@all_title.each do |all_title|
     #text = text.sub!(/#{all_title.title}/, "[#{all_title.title}](http://localhost:3000/notes/#{all_title.id})")
    #end
    @all_title.each do |all_title|
      text = text.sub!(/#{all_title.title}/, "[#{all_title.title}](https://my-note2.herokuapp.com/notes/#{all_title.id})")
     end
    @text = text
  end

  def new 
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to root_path
    else
      @notes = Note.all.order("created_at DESC")
      render "index"
    end
  end

  def edit
    @note = Note.find(params[:id])

  end

  def update
    @note = Note.find(params[:id])
 
    if @note.update(note_params)
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to root_path
  end

  def search
    @notes = Note.search(params[:keyword])
  end

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
  def note_params
    params.require(:note).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      options = {
        filter_html: true,
        autolink: true,
        space_after_headers: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        tables: true,
        hard_wrap: true,
        xhtml: true,
        lax_html_blocks: true,
        strikethrough: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer)
    end

    @markdown.render(text).html_safe
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>MyNote</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="padding-top: 5rem">
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= yield %>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>
</html>

app/views/notes/_header-edit.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <p class="navbar-brand" ><%= link_to 'My note', root_path, class:"link-none-white"%></p>
        </li>
        <li class="nav-item">
          <p class="navbar-brand" ><%= link_to '削除', note_path(@note),class:"link-none-white",
                        method: :delete,
                        data: { confirm: 'このノートを削除しますか?' } %></p>
        </li>
      </ul>
    <%= form_with(url: search_notes_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    </div>
  </div>
</nav>

app/views/notes/_header-show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <p class="navbar-brand" ><%= link_to 'My note', root_path, class:"link-none-white"%></p>
        </li>
        <%= render "nav-item" %>
      </ul>
    <%= form_with(url: search_notes_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    </div>
  </div>
</nav>

app/views/notes/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <p class="navbar-brand" ><%= link_to 'My note', root_path, class:"link-none-white"%></p>
        </li>

      </ul>
    <%= form_with(url: search_notes_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    </div>
  </div>
</nav>

app/views/notes/_nav-item.html.erb
        <li class="nav-item">
          <p class="navbar-brand" ><%= link_to '編集', edit_note_path(@note),class:"link-none-white" %></p>
        </li>
        <li class="nav-item">
          <p class="navbar-brand" ><%= link_to '削除', note_path(@note),class:"link-none-white",
                        method: :delete,
                        data: { confirm: 'このノートを削除しますか?' } %></p>
        </li>

app/views/notes/edit.html.erb
<%= render "header-edit" %>

  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <h2 class="text-center">編集</h2>
        <%= form_with(model: @note, local: true) do |form| %>
          <div class="form_group pt-4 pb-3">
            <%= form.label :title %><br>
            <%= form.text_field :title, class: "form-control"  %>
          </div>
          <div class="form_group pt-4 pb-3">
                <%= form.label :text %><br>
                <%= form.text_area :text, rows: 20, class: "form-control" %>
              </div>
              
              <div class="text-center"> 
                <%= form.submit "保存", class: "btn btn-primary" %>
              </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/notes/index.html.erb
<%= render "header" %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-2 text-align: left bg-light pt-3">
          <h5>ノート一覧</h5>
          <table>
            <% @notes.each do |note| %>
              <tr>
                <td><%= link_to note.title, note_path(note), class:"link-none" %></td>
              </tr>
            <% end %>
          </table>
        </div>
        <div class="col-9 pt-3">
          <%= form_with(model: @note, local: true) do |form| %>
              <div class="form_group pt-4 pb-5">
                <%= form.label :title %><br>
                <%= form.text_field :title, class: "form-control"  %>
              </div>
            
              <div class="form_group pt-4 pb-3">
                <%= form.label :text %><br>
                <%= form.text_area :text, rows: 20, class: "form-control" %>
              </div>
              
              <div class="text-center"> 
                <%= form.submit "保存", class: "btn btn-primary" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/notes/search.html.erb
<%= render "header" %>

<main>
  <div class="container py-4">
    <div class="mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
      <table>
        <% @notes.each do |note| %>
          <tr>
            <td><%= link_to note.title, note_path(note), class:"link-none" %></td>
          </tr>
        <% end %>
      </table>
      </div>
    </div>
  </div>
</main>

app/views/notes/show.html.erb
<%= render "header-show" %>
<main>
  <div class="container py-4">

    <div class="mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h3 class="fw-bold"><%= @note.title %></h3>
        <p class="col"><%= markdown(@text) %><%#= text_url_to_link(safe_join((h(@text)).split("\n"),tag(:br))).html_safe %></p>
      </div>
    </div>
  </div>
</main>